#!/bin/bash

# Check if the $PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
	echo "Error: Environment variable \$PYFILE is not set."
	exit 1
fi

# Run the Python script using python3
python3 "$PYFILE"
